INSERT INTO public.category (name) VALUES
                                ('Accessories'),
                                ('Clothing'),
                                ('Electronics'),
                                ('Footwear'),
                                ('Home & Kitchen'),
                                ('Home Appliances'),
                                ('Musical Instr.'),
                                ('Sports'),
                                ('Stationery'),
                                ('Toys & Games');


INSERT INTO product (sku, description, price, category_id) VALUES
                                                               ('SKU0001', 'Wireless Mouse with ergonomic design', 19.99, 3),
                                                               ('SKU0002', '4K Ultra HD Smart TV, 55 inches', 499.00, 3),
                                                               ('SKU0003', 'Stainless Steel Water Bottle, 1L', 29.50, 5),
                                                               ('SKU0004', 'Cotton T-Shirt, Unisex, Size M', 15.00, 2),
                                                               ('SKU0005', 'Noise-Cancelling Over-Ear Headphones', 120.00, 3),
                                                               ('SKU0006', 'USB-C to USB Adapter', 9.99, 3),
                                                               ('SKU0007', 'Leather Wallet with RFID Protection', 75.00, 1),
                                                               ('SKU0008', 'Yoga Mat with Non-Slip Surface', 35.00, 8),
                                                               ('SKU0009', 'Smartwatch with Heart Rate Monitor', 220.00, 3),
                                                               ('SKU0010', 'Ceramic Coffee Mug, 350ml', 12.50, 5),
                                                               ('SKU0011', 'Bluetooth Portable Speaker', 60.00, 3),
                                                               ('SKU0012', 'Backpack with Laptop Compartment', 85.00, 1),
                                                               ('SKU0013', 'Stainless Steel Cutlery Set, 24 Pieces', 18.00, 5),
                                                               ('SKU0014', 'Electric Guitar Starter Pack', 250.00, 7),
                                                               ('SKU0015', 'Running Shoes, Men''s Size 42', 42.00, 4),
                                                               ('SKU0016', 'Digital Bathroom Scale with Body Fat Analyzer', 27.99, 6),
                                                               ('SKU0017', 'Set of 6 Organic Cotton Socks', 14.99, 2),
                                                               ('SKU0018', 'DSLR Camera with 18-55mm Lens', 300.00, 3),
                                                               ('SKU0019', 'Hardcover Notebook, A5, 200 Pages', 8.99, 9),
                                                               ('SKU0020', 'Microwave Oven, 20L Capacity', 65.00, 6),
                                                               ('SKU0021', 'LED Desk Lamp with Adjustable Brightness', 23.50, 5),
                                                               ('SKU0022', 'Wireless Charger Pad for Smartphones', 19.00, 3),
                                                               ('SKU0023', 'Men''s Quartz Analog Watch with Leather Strap', 55.00, 1),
                                                               ('SKU0024', 'Wooden Chess Set with Folding Board', 30.00, 10),
                                                               ('SKU0025', 'Home Security Camera with Night Vision', 99.00, 3),
                                                               ('SKU0026', 'Aromatherapy Essential Oil Diffuser', 16.50, 5),
                                                               ('SKU0027', 'Professional Blender with 2L Jar', 40.00, 6),
                                                               ('SKU0028', 'Kids'' Educational Tablet Toy', 22.00, 10),
                                                               ('SKU0029', 'Mechanical Gaming Keyboard with RGB Lighting', 110.00, 3),
                                                               ('SKU0030', 'Pack of 10 Ballpoint Pens, Blue Ink', 7.50, 9);